version: "3.5"

services:
  virtuoso:
    image: "helldo/virtuoso"
    container_name: "virtuoso"
    ports:
      - "8890:8890"
    networks:
      - virtuoso
  api:
    image: "helldo/linkeddataapi"
    container_name: "api"
    ports:
      - "8080:80"
    networks:
      - virtuoso
networks:    
  virtuoso:
    driver: bridge
